### ISSUE TITLE
Эндпойнт аренды / Rental endpoint

### ISSUE THREAD

**Issue by DostovaK** [PashkaVRN/books_catalog#51]
Проверить работоспособность эндпойнта аренды (rents).

---------------------

Check rental endpoint (rents).

**Comment by PashkaVRN** [comment]
Просмотр книг в аренде по методу GET доступен только админ. составу ресурса.
Добавлять информацию в аренду может только админ. состав ресурса.
Реализован метод подсчета репутации пользователя в зависимость от того, вернул ли он книгу в указанный срок или нет.
